---
title: "SRM 2020 code analysis"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---

# Connect to Database and Getting data.

```{r}
library(tidyverse)

conn <- RSQLite::dbConnect(RSQLite::SQLite(), yaml::read_yaml("data/config.yaml")[['links_db_path']])
submissions_data_all = RSQLite::dbReadTable(conn, 'submissions') 
# accident_data = submissions_data %>% filter(challenge == "Accident Detection")
submissions_data_all = submissions_data_all %>%
  mutate(institute = "SRM") %>% 
  mutate(institute = replace(institute, str_detect(link, 'sastra'), "SASTRA")) %>% 
  filter(username != '[deleted]')

submissions_data = submissions_data_all %>% 
  filter(challenge != "Accident Detection")
RSQLite::dbDisconnect(conn)

```

# Finding Distance Metrics

```{r}

all_challenges = unique(submissions_data$challenge)

all_challenge_matrices = lapply(all_challenges, function(current_challenge){
  print(current_challenge)
  submissions_data_single_challenge = submissions_data %>%
    filter(challenge == current_challenge) %>%
    arrange(code)
  round(
    vimana::load_cache(
      fx = stringdist::stringdistmatrix, cache_dir = "data/cache/",
      a = submissions_data_single_challenge$code,
      b = submissions_data_single_challenge$code,
      method = 'jw'
    ), 3)
})

all_challenge_scores = lapply(1:length(all_challenges), function(i){
  # data.frame(apply(total_dist < 0.1, 1, sum) > 1)
  submissions_data_single_challenge = submissions_data %>%
    filter(challenge == all_challenges[i]) %>%
    arrange(code) %>%
    select(username)
  single_matrix = all_challenge_matrices[[i]]
  output = data.frame(submissions_data_single_challenge, score = apply(t(single_matrix), 1, sort)[2,])
  names(output)[2] = all_challenges[i]
  output
})

similarity_df = Reduce(function(x,y) merge(x, y, by = 'username', all = TRUE), all_challenge_scores) %>%
  setNames(c("username", all_challenges))

similarity_df_cleaned = similarity_df
similarity_df_cleaned[is.na(similarity_df_cleaned)] = 1
similarity_df_cleaned %>% head()
```

# Penalizing Plentiful hack

```{r}
hack_text = ">[=\\s]*\\d{5,}"
plentiful_hack_df = submissions_data %>%
  filter(str_detect(challenge, "Plentiful")) %>%
  mutate(
    # plentiful_hacked = str_detect(code, '495012538604'),
    plentiful_hacked = str_detect(code, hack_text),
    plentiful_extract = str_extract(code, hack_text)) %>%
  select(username, starts_with("plentiful"))


# plentiful_hack_df = submissions_data %>%
#   filter(str_detect(challenge, "Plentiful")) %>%
#   mutate(plentiful_hacked = str_detect(code, '\\d{5,}'),
#          plentiful_extract = str_extract(code, '\\d{5,}')) %>%
#   select(username, plentiful_hacked, plentiful_extract)


```

# Final score!

```{r}
total_score = submissions_data_all %>%
  group_by(institute, username) %>%
  summarize(total_score = sum(score))

report_final = merge(similarity_df_cleaned, total_score, all = T) %>%
  merge(plentiful_hack_df, all = T) %>%
  mutate(plentiful_hacked = replace(plentiful_hacked, is.na(plentiful_hacked), FALSE)) %>%
  mutate(plagiarism_1 = apply(.[,2:6] < .[,2:6] %>% apply(2, median, na.rm = TRUE)/5, 1, sum) > 1,
         plagiarism_2 =  apply(.[,3:6] <= 0.01, 1, sum) > 0)

report_selected = report_final %>% 
  filter(!plagiarism_1 & !plagiarism_2 & !plentiful_hacked)

write.csv(report_selected, yaml::read_yaml("data/config.yaml")[['selected_students_file']], row.names = F)

```

# Pretty graphs!

```{r}
library(igraph)
library(visNetwork)

all_graphs_distance = lapply(2:length(all_challenges), function(i){
  submissions_data_single_challenge = submissions_data %>%
    filter(challenge == all_challenges[i]) %>%
    arrange(code) %>%
    transmute(username, n = 1:n())
  single_matrix = all_challenge_matrices[[i]] == 0
  diag(single_matrix) = FALSE
  adj_list = igraph::as_data_frame(igraph::graph_from_adjacency_matrix(single_matrix))
  output = merge(submissions_data_single_challenge, adj_list, by.x = 'n', by.y = 'from') %>% 
    merge(submissions_data_single_challenge, by.x = 'to', by.y = 'n') 
  output %>% select(starts_with('username')) %>% 
    mutate(challenge = all_challenges[i])
}) %>% bind_rows()

all_graphs_distance_2 = all_graphs_distance %>% group_by(username.x, username.y) %>% 
  summarize(width = n(), title = paste0(challenge, collapse = ", "))
user_details = submissions_data %>% 
  select(username, institute) %>% 
  unique() %>% 
  filter(!duplicated(username)) %>% 
  merge(data.frame(
    institute = c("SRM", "SASTRA"),
    color = c("#1B9E77", "#D95F02")
  ))

other_usernames = user_details$username %>% Filter(function(x) !(x %in% all_graphs_distance_2$username.x), .)
final_graph = igraph::graph_from_data_frame(all_graphs_distance_2) 

final_graph = add_vertices(final_graph, length(other_usernames), name = other_usernames)



current_graph_usernames = user_details[match(igraph::get.vertex.attribute(final_graph, 'name'), user_details$username),]
final_graph = igraph::set_vertex_attr(final_graph, 'institute', value = current_graph_usernames$institute)
final_graph = igraph::set_vertex_attr(final_graph, 'color', value = current_graph_usernames$color)


V(final_graph)$title = V(final_graph)$name
V(final_graph)$size = 10
visIgraph(final_graph, physics = T, randomSeed = 42) %>% 
  visEdges(color = "black", arrows = list(to = FALSE, from = FALSE, middle = FALSE)) %>% 
  visIgraphLayout("layout.graphopt") %>%
  visOptions(width = "1600", height = "1200")


```


<!-- #Additional Testing -->
```{r eval=FALSE, include=FALSE}

# adj_matrix = all_challenge_matrices %>% lapply(function(x) {
#   x <= 0.01
# })
# 
# adj_matrix = adj_matrix[[4]]
# 
# igraph::plot.igraph(A2, vertex.size = 2, vertex.label.cex = 0.5,
#                     edge.arrow.size = 0.5, edge.arrow.width = 0.5,
#                     vertex.label = NA,
#                     vertex.tootip = 1:1348,
#                     # lty=0,
#                     layout = igraph::layout_with_graphopt(A1),
#                     # vertex.color = V(A1)$community
# )
# 
# all_usernames = submissions_data$username %>% unique()
# 
# igraph::plot.igraph(final_graph, vertex.size = 2, vertex.label.cex = 0.5,
#                     edge.arrow.size = 0.5, edge.arrow.width = 0.5,
#                     vertex.label = NA,
#                     vertex.tootip = 1:1348,
#                     # lty=0,
#                     layout = igraph::layout_with_graphopt(final_graph),
#                     vertex.color = V(final_graph)$color
#                     # vertex.label = V(final_graph)$name
# )
# ?visIgraph
# igraph::layougrap
# g <- make_ring(10, dir=TRUE)
# al <- igraph::graph_from_data_frame(g, mode="out")

# A1 = igraph::graph_from_adjacency_matrix(adj_matrix, diag = F)
# # plot(A1, vertex.size = 5, igraph::layout_(A1, igraph::n()))
# # plot(A1, vertex.size = 5, layout=igraph::layout_nicely(A1))
# A2 = igraph::cluster_label_prop(A1)
# V(A1)$community <- A2$membership
# colrs <- adjustcolor( c("gray50", "tomato", "gold", "yellowgreen"), alpha=.6)
# A2$membership = A2$membership[A2$membership %in% which(table(A2$membership) >=2)]
# plot(A2, A1,vertex.size = 2,  vertex.label.cex = 0.5,vertex.label = NA)
```

